# Generated by Django 4.2 on 2024-09-08 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_location'),
        ('servicedesk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerquery',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='contact', to='servicedesk.contact'),
        ),
        migrations.AlterField(
            model_name='customerquery',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='contact', to='core.category'),
        ),
    ]
