# Generated by Django 4.2 on 2024-09-08 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_location'),
        ('servicedesk', '0002_customerquery_contact_alter_customerquery_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerquery',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.category'),
        ),
    ]
