# Generated by Django 4.2 on 2024-09-08 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_location'),
        ('servicedesk', '0003_alter_customerquery_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerquery',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='userauth', to='core.subcategory'),
        ),
    ]
