# Generated by Django 4.2 on 2024-09-09 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicedesk', '0004_alter_customerquery_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerquery',
            name='agent',
        ),
    ]
