# Generated by Django 4.2 on 2024-09-09 04:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('servicedesk', '0005_remove_customerquery_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerquery',
            name='escalatedto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='escalationuser', to=settings.AUTH_USER_MODEL),
        ),
    ]
